import string
import os

MYARCH = os.uname()[4]

COMMON_SOURCES = [ ]
TARGETS = {
    'wxSierpinski' : [
        'control_panel.cpp',
        'frontend.cpp',
        'glpanel.cpp',
        'mainframe.cpp',
        'scenethread.cpp',
    ]
}
INCLUDE_DIRS = [
    '#/libsierp/include',
]
LIBS = [
    'sierp',
    'm',
    'GL',
    'GLU',
]
LIB_DIRS = [
    '../source',
    '../../libsierp/source',
]

# You shouldn't need to modify below this line.

Import('amenv')
menv = amenv.Copy()

#### Section for wxWidgets
menv.Append(CCFLAGS=['-DwxUSE_GLCANVAS=1'])
menv.ParseConfig('wx-config --cflags --libs --gl-libs')
#### 

menv.Append(CPPPATH=INCLUDE_DIRS)
menv.Append(LIBS=LIBS, LIBPATH=LIB_DIRS)

for target in TARGETS.keys():
    #
    # If we're building on an x86_64 architecture, then only build
    # the application for that architecture.  (i.e. we can't
    # cross-build to i386 without those development libraries
    #
    build = 1
    if MYARCH == 'x86_64':
        if( string.find(menv.WORKING_BUILD_TYPE, MYARCH ) < 0 ):
            build = 0

    if build:
        sources = TARGETS[target]
        menv.Program(target, sources)
        menv.Install(target)

